FROM covid-demo-basis

WORKDIR /usr/src/app
RUN ls
RUN git clone https://github.com/Shaul1321/covid-ai2 #REDO
WORKDIR /usr/src/app/covid-ai2

# run streamlit

EXPOSE 8080
COPY . .
CMD ["bash", "startup.sh"]

